#ifndef JUMPER_ULOGGER_LOGGING_CONFIG_SAMPLE_H_H
#define JUMPER_ULOGGER_LOGGING_CONFIG_SAMPLE_H_H

#define PLATFORM_CC3200     1
#define PLATFORM_NRF52      2

#define ULOGGER_PLATFORM PLATFORM_CC3200

#define GATT_BUFFER_SIZE 200

#endif //JUMPER_ULOGGER_LOGGING_CONFIG_SAMPLE_H_H
