#ifndef JUMPER_ULOGGER_LOGGING_CONFIG_SAMPLE_H_H
#define JUMPER_ULOGGER_LOGGING_CONFIG_SAMPLE_H_H

#include "ulogger.h"
#include "app_util_platform.h"

#define ULOGGER_PLATFORM PLATFORM_NRF52

#define ULOGGER_ENTER_CRITICAL_SECTION() CRITICAL_REGION_ENTER()
#define ULOGGER_EXIT_CRITICAL_SECTION() CRITICAL_REGION_EXIT()

#define GATT_BUFFER_SIZE 200
#define LOG_SEND_PERIOD_MS 5000

#endif //JUMPER_ULOGGER_LOGGING_CONFIG_SAMPLE_H_H
